spring:
  application:
    name: hw11
  datasource:
    url: jdbc:h2:mem:hw5db
    driverClassName: org.h2.Driver
    username: hw5db
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
application:
  issue:
    max-allowed-books: 4
management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: env, prometheus, health, info, metric